package dev.core.attribute;

public enum AttributeType {
	MAX_HEALTH, MANA, ARMOR, MAGIC_RESIST, ATTACK_DAMAGE, ABILITY_POWER, ATTACK_SPEED, LETHALITY, ARMOR_PENETRATION,
	CRIT_CHANCE, MOVE_SPEED, HEALTH_REGEN, MANA_REGEN, HEAL_SHIELD_POWER, HEALING_REDUCTION;
}
