name: Project-D
version: '1.0-SNAPSHOT'
main: dev.bukkit.DMain
api-version: '1.21'
depend: [ProtocolLib]
commands:
  giveItem: 
  saveItem: 
  showProgress: 
  selectActive: 
  showStats: 
  setXp: 
  dungeon:
    description: Main dungeon command
    usage: /dungeon <generate|tp> [world_name]