package dev.core.stat;

public enum StatType {

	ATTACK_DAMAGE, ABILITY_POWER, ARMOR, MAGIC_RESIST,
	ATTACK_SPEED, MOVE_SPEED, ABILITY_HASTE, LETHALITY, 
	ARMOR_PENETRATION, CRIT_CHANCE, HEAL_AND_SHIELD_POWER,
	
	HEALTH_MAX, HEALTH_REGEN,
	MANA_MAX, MANA_REGEN
	
	
	
}
